### ISSUE TITLE
Registration system with email confirmation

### ISSUE THREAD

**Issue by maciejzj** [MaciejZj/balloonS#9]
The email should be confirmed by admin.
https://www.youtube.com/watch?v=F0VReccd_44

**Comment by mmaccho** [comment]
- [x]  reCAPTCHA
- [x]  Remember data in form in sign up system
- [x]  Make password and nickname requirements visible visible only after hovering over question mark
- [x]  Check length of the authentication code generated - needs to be under 11 digits long
